config/routes.rb
Rails.application.routes.draw do

  resources :carousels

  match "templates/prev" => "templates#prev", :via => :post
  match "templates/next" => "templates#next", :via => :post
  match "templates/curr" => "templates#curr", :via => :post

  resources :templates

  resources :news
  get '/news/:id/:title' => 'news#show', :as => :news_with_title

  root to: 'home#index'
  get 'home/resume', to: 'home#resume'

  devise_for :users
  resources :posts

  resources :accounts

  resources :projects

  devise_scope :user do
    get '/admin' => 'devise/sessions#new', :as => 'admin_login'
  end

end

app/models/carousel.rb
class Carousel < ActiveRecord::Base
end

app/controllers/carousels_controller.rb
class CarouselsController < ApplicationController
  before_action :set_carousel, only: [:show, :edit, :update, :destroy]

  # GET /carousels
  # GET /carousels.json
  def index
    @carousels = Carousel.all
  end

  # GET /carousels/1
  # GET /carousels/1.json
  def show
  end

  # GET /carousels/new
  def new
    @carousel = Carousel.new
  end

  # GET /carousels/1/edit
  def edit
  end

  # POST /carousels
  # POST /carousels.json
  def create
    @carousel = Carousel.new(carousel_params)

    respond_to do |format|
      if @carousel.save
        format.html { redirect_to @carousel, notice: 'Carousel was successfully created.' }
        format.json { render :show, status: :created, location: @carousel }
      else
        format.html { render :new }
        format.json { render json: @carousel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carousels/1
  # PATCH/PUT /carousels/1.json
  def update
    respond_to do |format|
      if @carousel.update(carousel_params)
        format.html { redirect_to @carousel, notice: 'Carousel was successfully updated.' }
        format.json { render :show, status: :ok, location: @carousel }
      else
        format.html { render :edit }
        format.json { render json: @carousel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carousels/1
  # DELETE /carousels/1.json
  def destroy
    @carousel.destroy
    respond_to do |format|
      format.html { redirect_to carousels_url, notice: 'Carousel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carousel
      @carousel = Carousel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carousel_params
      params.require(:carousel).permit(:controller_name, :image_link, :image_asset_link, :main_text, :sub_text)
    end
end

app/helpers/carousels_helper.rb
module CarouselsHelper
end

app/views/carousels/_form.html.erb
<%= form_for(@carousel) do |f| %>
  <% if @carousel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carousel.errors.count, "error") %> prohibited this carousel from being saved:</h2>

      <ul>
      <% @carousel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :controller_name %><br>
    <%= f.text_field :controller_name %>
  </div>
  <div class="field">
    <%= f.label :image_link %><br>
    <%= f.text_field :image_link %>
  </div>
  <div class="field">
    <%= f.label :image_asset_link %><br>
    <%= f.text_field :image_asset_link %>
  </div>
  <div class="field">
    <%= f.label :main_text %><br>
    <%= f.text_field :main_text %>
  </div>
  <div class="field">
    <%= f.label :sub_text %><br>
    <%= f.text_field :sub_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carousels/edit.html.erb
<h1>Editing carousel</h1>

<%= render 'form' %>

<%= link_to 'Show', @carousel %> |
<%= link_to 'Back', carousels_path %>

app/views/carousels/index.html.erb
<h1>Listing carousels</h1>

<table>
  <thead>
    <tr>
      <th>Controller name</th>
      <th>Image link</th>
      <th>Image asset link</th>
      <th>Main text</th>
      <th>Sub text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carousels.each do |carousel| %>
      <tr>
        <td><%= carousel.controller_name %></td>
        <td><%= carousel.image_link %></td>
        <td><%= carousel.image_asset_link %></td>
        <td><%= carousel.main_text %></td>
        <td><%= carousel.sub_text %></td>
        <td><%= link_to 'Show', carousel %></td>
        <td><%= link_to 'Edit', edit_carousel_path(carousel) %></td>
        <td><%= link_to 'Destroy', carousel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Carousel', new_carousel_path %>

app/views/carousels/new.html.erb
<h1>New carousel</h1>

<%= render 'form' %>

<%= link_to 'Back', carousels_path %>

app/views/carousels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Controller name:</strong>
  <%= @carousel.controller_name %>
</p>

<p>
  <strong>Image link:</strong>
  <%= @carousel.image_link %>
</p>

<p>
  <strong>Image asset link:</strong>
  <%= @carousel.image_asset_link %>
</p>

<p>
  <strong>Main text:</strong>
  <%= @carousel.main_text %>
</p>

<p>
  <strong>Sub text:</strong>
  <%= @carousel.sub_text %>
</p>

<%= link_to 'Edit', edit_carousel_path(@carousel) %> |
<%= link_to 'Back', carousels_path %>