config/routes.rb
Rails.application.routes.draw do

  resources :carousels

  match "templates/prev" => "templates#prev", :via => :post
  match "templates/next" => "templates#next", :via => :post
  match "templates/curr" => "templates#curr", :via => :post

  resources :templates

  resources :news
  get '/news/:id/:title' => 'news#show', :as => :news_with_title

  root to: 'home#index'
  get 'home/resume', to: 'home#resume'

  devise_for :users
  resources :posts

  resources :accounts

  resources :projects

  devise_scope :user do
    get '/admin' => 'devise/sessions#new', :as => 'admin_login'
  end

end

app/models/news.rb
class News < ActiveRecord::Base
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.where(archived:false).order('created_at DESC')
    @is_admin = is_admin
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @is_admin = is_admin
  end

  # GET /news/new
  def new
    @news = News.new
    restricted
  end

  # GET /news/1/edit
  def edit
    restricted
  end

  # POST /news
  # POST /news.json
  def create
    restricted
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    restricted
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    if !is_admin
      respond_to do |format|
        format.html { redirect_to action: "index" }
        format.js { head :ok }
      end
    else
      @news.destroy
      respond_to do |format|
        format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private



    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :content, :archived)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, {:style=>"width:90%"} %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content,{:style=>"width:90%;height:300px"} %>
  </div>
  <div class="field">
    <%= f.label :archived %><br>
    <%= f.check_box :archived %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>


        <%= link_to 'Show', @news %>

        <%= link_to 'Destroy', @news, method: :delete, data: { confirm: 'Are you sure?' } %>
<br>
<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<div class="center-feature">
<center><h1 class="text-thin">Posts</h1></center>

  <% @news.each do |news| %>
    <div class="news-article" style="position:relative;margin:80px 0">
    <div style="padding-right:100px">
      <h3 style="display:inline"><%= link_to news.title, news_with_title_path(news, :title=>news.title.tr(' ', '_')) %></h3>
    </div>
    <div style="margin-bottom:20px" class="pull-right"><%= news.created_at.localtime.strftime("%b %d, %Y") %></div>

    <p style="padding-top:20px"><%= news.content.html_safe %></p>

    <% if @is_admin %>
      <%= news.archived %>
      <%= link_to 'Edit', edit_news_path(news) %>
    <% end %>
    <hr>
    </div>
  <% end %>
</div>
<% if @is_admin %>
  <%= link_to 'New News', new_news_path %>
<% end %>

app/views/news/new.html.erb
<h1>New news</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<div class="center-feature">


  <div class="news-article" style="position:relative;margin:80px 0">
    <div style="padding-right:100px">
      <h3 style="display:inline"><%= link_to @news.title, news_with_title_path(@news, :title=>@news.title.tr(' ', '_')) %></h3>
    </div>
    <div style="margin-bottom:20px" class="pull-right"><%= @news.created_at.localtime.strftime("%b %d, %Y") %></div>

    <p style="padding-top:20px"><%= @news.content.html_safe %></p>

    <% if @is_admin %>
    <%= @news.archived %>
    <%= link_to 'Edit', edit_news_path(@news) %>
    <% end %>
    <hr>
  </div>

</div>
<% if @is_admin %>
<%= link_to 'New News', new_news_path %>
<% end %>